name: quote

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.15.1
      - run: npm i
      - name: Generate quote
        run: npm run gen
      - name: Update README.md
        run: |
          git config --global user.email "funnystar320@gmail.com"
          git config --global user.name "mercenarioZ"
          git add .
          git commit -m "Updated README.md" || echo "No changes"
          git push
